### ISSUE TITLE
fatal error: ros/console.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by ZhaTianjun** [linyicheng1/teb_local_planner#7]
您好，我在编译时出现了这个问题，请问该怎么解决？

**Comment by linyicheng1** [comment]
g2o_types/vertex_timediff.h 文件中的 intclude ros/console.h 去掉


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linyicheng1/teb_local_planner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午2:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[linyicheng1/teb_local_planner] /home/z/a_sanshi/teb_local_planner-master/src/../inc/../inc/../inc/g2o_types/vertex_timediff.h:52:25: fatal error: ros/console.h: 没有那个文件或目录 (Issue #7)





 
您好，我在编译时出现了这个问题，请问该怎么解决？
