### ISSUE TITLE
编译时报错 error: optimal_planner.o: undefined reference to symbol '_ZN3g2o18get_monotonic_timeEv'

### ISSUE THREAD

**Issue by Tiedan12138** [linyicheng1/teb_local_planner#9]
已经配置了g2o库，编译的时候还是报错：
 error: optimal_planner.o: undefined reference to symbol '_ZN3g2o18get_monotonic_timeEv'
error: /home/zy/g2o/build/lib/libg2o_stuff.so.0.1: error adding symbols: DSO missing from command line
网上有人说是ros自带的g2o库和独立的g2o库有冲突，但是我的ros并没有自带g2o库还是会有这个问题，请问有什么解决思路吗

**Comment by linyicheng1** [comment]
g2o版本不对

**Comment by Tiedan12138** [comment]
> g2o版本不对

请问您装的是哪个版本，我已经试了两个版本了还是不行
